Ncnews 6
Controllah-Gabi/news-api pull request #4
Opened 2022-11-16 10:22 UTC by Controllah-Gabi

2022-11-16 10:53 UTC, Harrison365 requested changes
Hey Controllah :) 
Please...
-Make sure your comments are on a key of comments, not comment (I know this is picky).
-Your forEach will require a .length check to avoid false positives.
-Make a test for an existing article that has no comments. this will require you to make a second pool.query to check the article exists before selecting comments by ID.

Let us know if you have any issues :)

2022-11-16 12:04 UTC, Harrison365 requested changes
Great :) 
Please could you add a test for an article that exists but has 0 comments. then you should be good 👍

2022-11-17 08:54 UTC, emilyb93 commented on __tests__/app.test.js
> +    })
Id like to see a test for if the review_id is not a number but the rest of the URL is fine. Soemthing like `/api/articles/sports/comments`

2022-11-17 08:55 UTC, emilyb93 requested changes
One more test please

2022-11-17 09:46 UTC, hevmag approved these changes
Nice! good to merge

2022-11-17 09:48 UTC, merged