pr request sent, ticket 7 almost done
Controllah-Gabi/news-api pull request #5
Opened 2022-11-17 14:04 UTC by Controllah-Gabi

first review

2022-11-17 14:27 UTC, emilyb93 commented on __tests__/app.test.js
>      })
I would remove the article_id from the object here, you are already providing it in the url and as such you can take it from the url in your controller from req.params

2022-11-17 14:28 UTC, emilyb93 commented on __tests__/app.test.js
>      })
I think theres a few more tests here to do as well;
Posting to an article number that doesnt exist
posting to an article with an id that isnt even a number
posting a comment that doesnt even have a username
posting a comment that has a valid username but not a body?

2022-11-17 14:29 UTC, emilyb93 commented on utils/db.js
> +        }
You dont need this anymore since you are checking this by dealing with foreign key errors :)

2022-11-17 14:30 UTC, emilyb93 requested changes
Few more tests to do, but this is looking great so far!

2022-11-17 15:07 UTC, hevmag requested changes
Testing is looks brill based on suggestions! I would have another look at what Emily is talking about with regards to username a bit more though, an invalid username value should be handled in your PSQL error handling middleware in your app (error code to look out for is 23503)

2022-11-17 16:17 UTC, Harrison365 requested changes
Hey Controllah :) ,

Please...
-Change the author in the req.body to username, I believe that's what the ticket asked for.
-Please test and error handle for article doesn't exist, invalid id (e.g. a string), req.body has missing fields (username, body, and both).

Thanks.

2022-11-18 10:10 UTC, Harrison365 approved these changes
Looks good :)

2022-11-18 10:17 UTC, merged